### ISSUE TITLE
EqualSisters category argument

### ISSUE THREAD

**Issue by jbellik** [syntax-prosody-ot/main#136]
The current implementations of EqualSisters don't actually look at the category argument to the function at all. So it's misleading to have the categories listed for ES on the interface. They should be removed.

And/Or: we can also consider implementing category-specific versions of ES.

**Comment by maxTarlov** [comment]
I've removed the options for categories in equalSisters constraints. Should I try to implement a category specific version? The implementation that I was thinking of would say "assign a violation for every node of category x that has a sister of a different category" but this won't be different from the non-specific version except when clitics are used (otherwise the recursive category and the terminal category are the only two categories that can be sisters in the trees generated by GEN; equalSisters-phi will assign the same violations as equalSisters-w, equalSisters-i will never assign any violations unless i is the terminal or recursive category)

**Comment by jbellik** [comment]
I don't think we need a category-specific version, since to my knowledge no one is using such a constraint or has proposed to do so.
