### ISSUE TITLE
Change AlignLeftClitic to take an array of variable names rather than a single one

### ISSUE THREAD

**Issue by rbibbs** [syntax-prosody-ot/main#210]
@maxTarlov Jenny said to assign you to this, so if you have the time it would be much appreciated!

Currently AlignLeftClitic checks the ID of a node based on a name you give it. I.e. if my clitic is "gui'", I give AlignLeftClitic "gui'" to look for to evaluate its position. However, because many clitics of the same type are different lexical items, it would be great if AlignLeftClitic could be given multiple IDs to check for; e.g. ["gui'", "yu'", "hao"] and then it evaluates any of these that are found within the inputs.

Let me know if this doesn't make sense or if it's unclear in any way!

**Comment by jbellik** [comment]
New plan: I'm reassigning this to Iva because Max is currently working on upgrades to save/load analysis to make it compatible with Match options.

Iva, the alignLeftClitic code is found in constraints/nongeneral/alignLeftClitic.js. You should move it out of nongeneral up into the  main constraints folder so that it gets added to the build files.

**Comment by jbellik** [comment]
Update: I moved it out of "nongeneral"

**Comment by jbellik** [comment]
I just implemented this after all.
