### ISSUE TITLE
Binarity + subcategorization

### ISSUE THREAD

**Issue by jbellik** [syntax-prosody-ot/main#214]
Nick Van Handel (@nvh4 )'s analysis uses BinLeaves that is subcategorized to count words only for the maximal phi. We need to add this to the interface somehow in a minimally noticeable way.

One option would be to add a checkbox under BinMinLeaves that calls the custom constraint under the hood, although this may run into some issues with the way constraints are processed by interface1.js and built_in_analyses.js. However, I think we can avoid these problems if we use the right class names. (I hope.)

**Comment by jbellik** [comment]
Better solution: add options to binMinLeaves (and binMaxLeaves if you have time) to specify that you only want to look at, e.g., maximal phis.

Might as well add the "minimal" option too

Add it to the interface (same layout as custom Match)

**Comment by maxTarlov** [comment]
Some Issues with the above: 

* NVH's analysis uses both binX2Words and binX2Words_maxPCat. Currently, the interface does not support using one constraint with two different option sets, so having maximal/minimal options won't really help us; I will have to add an input to the constraints class separate from binMaxLeaves
* Currently the built-in systems can't deal with the drop-downs for maximality and minimality, which is why it doesn't work for the custom match constraint, so again the maximality/minimality options aren't going to be helpful. 

With this in mind, I think it would be most efficient time-wise to go with the first plan (calling a custom constraint under the hood). I still hope to work on making binarity optionable in the future, but it there are too many issues with it to get it done by NINJAL.

**Comment by jbellik** [comment]
Oh shoot. I didn't think about that. I guess that'll be a design issue for
the winter quarter. Do whatever seems like the most efficient solution for
now. Or: Iva said she had time to do another issue before Monday, so if you
are short on time, you could also ask her to work on this one.

**Comment by maxTarlov** [comment]
I wrote a constraint called binMin_requireMaximal and added it to the interface. This is the most efficient solution since it doesn't require stipulation in the built-in and save/load code to work. It looks pretty ugly in the tableaux, but I feel that this is the best solution for the time being. It is also more transparent than calling a separate function under the hood. These changes are in pull request #237
