### ISSUE TITLE
Make input string representations express all input information

### ISSUE THREAD

**Issue by nkalivoda** [syntax-prosody-ot/main#246]
For sCat information like "has overt head" and "has lexical head", we need the representation in the string version of the input to express these distinctions. Right now it's being neutralized. We could use boundary symbols other than square brackets, or somehow annotate the square brackets.

This is **crucial** for looking at input strings in OTWorkplace. Right now it's possible to have identical-looking inputs that are actually substantively different!

**Comment by jbellik** [comment]
Change parenthesizeTree() to represent xps that are marked as "func: true" with [f ] instead of plain [ ], and  xps marked "silentHead: true" with [sh ] instead of plain [ ].
Nodes that are functional and silent-headed should be marked as [f.sh ].

This actually needs to generalize to all categories, such as intonational phrases i, and also *new categories*
e.g., if the tree contains a node of category "phase" that is labeled functional and silent, and showNewCats: true, then ... [phase.f.sh    ]

**Comment by ColinAChen** [comment]
Is this issue done or are there changes to be made?

**Comment by jbellik** [comment]
Also complete I think.
