### ISSUE TITLE
Align-Focus

### ISSUE THREAD

**Issue by nkalivoda** [syntax-prosody-ot/main#318]
Truckenbrodt (1999) has a constraint Align-Foc. His exact words:

<img width="685" alt="Screen Shot 2020-02-25 at 10 22 52 AM" src="https://user-images.githubusercontent.com/12573882/75238362-cc375a00-57b8-11ea-969f-6f1cfe8e89b8.png">

There is also a left-aligning version.

To do this, we should have a "foc" attribute, which can be freely placed on terminal and non-terminal nodes of the sTree.

The constraints should have "foc" as the "sCat" (technically an "sAttribute"), and ideally would have a custom pCat argument. Something like:

**Align(sTree,pTree,foc,pCat,direction)**
For every node S with attribute "foc" in sTree, assign a violation if the _direction_-edge of S is not aligned to the _direction_-edge of a node of category pCat in pTree.

**Comment by nkalivoda** [comment]
As @jbellik suggested, we could also have MatchSP(sTree,pTree,foc,pCat). Even though I haven't seen this proposed anywhere, it makes sense. It could go under "more constraints" in the relevant section.

Like with Align-Foc, this would really need to treat the foc→pCat mapping differently from sCat→pCat. We would need to say that a focused constituent of any sCat should match a pCat, not necessarly one with the expected sCat↔pCat correspondence. So it should be possible to have foc→ι, foc→φ, and foc→ω constraints, where it doesn't matter whether foc is CP, XP, or X⁰.

**Comment by jbellik** [comment]
stree = [ a b.foc ], where a and b are x0s (although they could've been wrapped in xps, it doesn't matter)
ptree = (a b)
alignFocLeft(stree, ptree, 'phi') --> assign a violation for every node marked foc:true in the stree that isn't at the left edge of a phi in ptree
here, alignFocLeft(stree, ptree, 'phi') = 1 violation since b is foc:true but isn't at the left edge of a phi

Instead of checking if node.cat === scat, you check if they have foc: true

**Comment by jbellik** [comment]
The other thing to adjust is going to be:
if(!catsMatch(sCat, pNode.cat))
Instead, we need to check if pNode.cat === pCat
pCat is an argument

Function signature should be:
AlignFoc(sTree,pTree,pCat,direction)
