### ISSUE TITLE
Info contents

### ISSUE THREAD

**Issue by maxTarlov** [syntax-prosody-ot/main#381]
A few info blocks on the main branch do not contain anything except the word "info." I filled in most of these in #380 , but I wasn't entirely sure what to put for "Head Requirements" or "Add XP clitics directly under root" in the Automatic Input Generation Options.

**Comment by jbellik** [comment]
Head requirements: To require all X0s to be at the very left edge of their XP, select "Heads must be perfectly left-aligned." This will admit [a [b]] and [[a][b]] but not [[a]b[c]] or [[a]b]. To admit [[a]b[c]] while still excluding [[a]b], select "Heads must be left-aligned." To require all X0s be at the very right edge of their XP, select "Heads must be perfectly right-aligned." This will admit [[a]b] and [[a][b]], but not [[a]b[c]] or [a[b]]. To admit [[a]b[c]] while still excluding [a[b]], select "Heads must be right-aligned."

... Actually, there's currently no way to get [[a] b [c]] because we didn't include a "Treat X' as invisible" option which would set max branching to 3 instead of the current 2. I'll have to make an issue for that.

I'll get to "Add XP clitics..." tomorrow.
