### ISSUE TITLE
Disallowing adjuncts with an XP clitic beneath the root

### ISSUE THREAD

**Issue by rbibbs** [syntax-prosody-ot/main#429]
Having allow adjuncts **unchecked** while wanting an XP clitic beneath the root produces no input structures.
We should be able to produce solely head+complement type structures while also having an XP clitic attached directly under the root.

**Comment by jbellik** [comment]
Hopefully this can be easily fixed by reordering the adjunction filter relative to the line that adds the clitics.

With adjunction on and terminal string "a b" + add XP clitics, we want these 3 outputs:
1. [[a [b]] [x.clitic]]
2. [[[a] b] [x.clitic]]
3. [[[a] [b]] [x.clitic]]

With adjunction OFF and terminal string "a b" + add XP clitics, we want these 2 outputs:
1. [[a [b]] [x.clitic]]
2. [[[a] b] [x.clitic]]
