### ISSUE TITLE
CP Root and head-alignment issue

### ISSUE THREAD

**Issue by rbibbs** [syntax-prosody-ot/main#430]
When you have Root as CP, then “Heads must be on the left edge” incorrectly produces inputs with the head on the right edge if the root of the tree is a CP, (1)

(1) {[[a] [[b] c]]} ; {[a [[b] c]]} (with “remove mirror images” checked)

This problem doesn’t happen with an XP root

**Comment by jbellik** [comment]
With these settings, on the master branch we currently get:
1. | {a [b [c]]}
2. | {a [[b] [c]]}
3. | {[a] [b [c]]}
4. | {[a] [[b] [c]]}
5. | {[a [b]] [c]}
6. | {[a [b [c]]]} <-- the good version of 7 -- we want this one but not (7)
7. | {[a [[b] c]]} <-- bad because c is an x0 that appears on the right: it's the rightmost child of [[b] c]
8. | {[a [[b] [c]]]}
9. | {[[a] [b [c]]]} <-- the good version of (10)
10. | {[[a] [[b] c]]} <-- bad for the same reasons as (7)
11. | {[[a] [[b] [c]]]}

With adjunction disallowed, we correctly only get:
{a [b [c]]}
