### ISSUE TITLE
MatchSP, MatchPS - combining subcategories with lexical, overtly headed options

### ISSUE THREAD

**Issue by nvh4** [syntax-prosody-ot/main#442]
Issue with assessing (non-)maximal and (non-)minimal status when either the "lexical" or "overtly headed" option is selected. 
Right now subcategory status is based on the entire tree, but should instead be determined based on the set of lexical and/or overtly headed phrases.

For instance, given the syntax: [<sub>FuncP</sub> X [<sub>LexP1</sub> Y [<sub>LexP2</sub> Z ]]]

When "lexical" is selected, LexP1 should be considered maximal because it is the highest lexical phrase (i.e., it is the highest XP within the set of lexical XPs that are visible to MatchXP-Lex). However, SPOT will consider it to be non-maximal because it is dominated by FuncP (i.e., it is not maximal if one considers the entire tree). Thus, Match(XP-Max-Lex,phi) will incorrectly ignore LexP1. A similar issue arises when "overtly headed" is selected.

Needed: SPOT should first filter out non-lexical (or non-overtly-headed) phrases, and then determine which phrases are max, min, etc.

**Comment by jbellik** [comment]
Please pair program on this as an educational exercise.

**Comment by jbellik** [comment]
We need to add options requireLexical and requireOvertHead to markMinMax(). These can be passed in from MatchSP / MatchPS.

(We won't build support to optionally parse LexP1 as maximal from the example in the original post.)

**Comment by jbellik** [comment]
Proposed implementation:
- create function removeSpecifiedNodes() (modeled on trimRedundantNodes() and maybe also trimSilentTerminals() from treeTrimming.js). It should take the attribute of nodes to be trimmed as an option, and remove whatever nodes have that attribute == true from a deep copy of that tree (use copyTree())
- markMinMax can call removeSpecifiedNodes() with whatever appropriate attributes as the option.
- matchSP will continue to call markMinMax as before but with options.

[ func lex [complementXP] ] --> [lex [complementXP]]
[ func [complementXP] ] --> [complementXP]     <- trimRedundantNodes could handle the transformation from [[complementXP]] to [complementXP]

[.f [subj] [verb] ] --> [.dummy [subj] [verb]]: create some dummy category to replace a functional root to maintain tree status. {id: 'root', cat: 'dummy', children: [{subj}, {verb}]}

**Comment by 3ddiehead** [comment]
I am having difficulty understanding how to implement this. If an xp node has the attribute func == true or silentHead == true, then it is implied that the word it projects from has this quality. This "removeSpecifiedNode" process should start with the removal of a specified head and the ramifications should be propagated through the tree OR it should start with the removal of the maximal node and the effect should be propagated down through to the head. Either way, it is essential to make the link between maximal projections and their heads explicit in the coding of trees.

Without an explicit link, there is no way to know from observing a node which terminal to remove and which nodes between them should be removed or dummified.

Please advise.

**Comment by jbellik** [comment]
Sorry I just saw this. You bring up an excellent point. Let's work off the assumption that functional heads will also either be labeled as "func:true", or won't be present in the tree itself (e.g. if they have no phonological content, the analyst may choose to omit them from the tree altogether). Likewise for heads that are silent -- assume that if they aren't marked "silentHead: true" then they have phonological content.

So essentially I want you to assume that anything that needs to be pruned out of the tree will be explicitly marked as having the relevant attribute. Don't assume that attributes necessarily percolate up/down, because the analyst could also have built the tree in a way that doesn't overtly represent (e.g.) traces. We will adjust the instructions on the interface to make it clear that if you want heads to ever be ignored because they are functional / silent, you must mark them as such.

Does that clear things up? We will leave the burden of labeling trees appropriately to the analyst for maximum transparency in SPOT's behavior.

**Comment by nvh4** [comment]
My understanding is that ZP should be considered non-maximal: even though its parent is a FuncP, it is still dominated at some level by a LexP.

It is true that Ishihara's (2014) definition says a "maximal lexical phrase" is "not immediately dominated by another lexical XP" but this formulation seems strange to me, at least intuitively. I'm not sure if there is a reason the definition mentions immediate domination, because from what I remember, his analysis does not involve any examples like the one you provided, in which a FuncP intervenes between two LexPs.

I think there's a principled reason to change the original definition, too: this definition asks for the maximal lexical phrases to be mapped to maximal phi. However, if both XP and ZP are maximal lexical phrases, neither can be mapped to a maximal phi at the same time. It's reminiscent of the Anti-Match constraints I presented last month.

Unless I'm missing a reason why we need to refer to immediate domination, I think trimming the functional nodes should work fine.

**Comment by jbellik** [comment]
Ok, that is good to hear. It's a little hard for me to think through this properly because I've never tried to use the functional/lexical distinction. Maybe I should talk to Junko about it before we finalize an implementation.

**Comment by jbellik** [comment]
Here are a couple of simple, concrete examples of the lex-func-lex situation which I found helpful for thinking through this:

[VP V [DP D [NP N]]] --> VP and NP are lexical, DP is functional (right??)
We probably don't want NP to be maximal. This is in line with what I understand our current implementation to be.

[NP N [PP P [NP N]]] --> both NPs* are lexical, intervening PP is functional
*Here I've left out the DP layers; let's say they aren't visible at all since the Ds are phonologically empty and they can be trimmed out by Elfnerian Match.
Again, I believe we don't want the lower NP to be counted as a maximal lexical projection, since it's contained inside another NP.

[NP N1 [DP D [NP N2]]] --> NPs are lexical, DP is functional
Again it seems very reasonable here to say that only NP1 is maximal.

All of these support the idea that we should revise the original Ishihara definition and define the maximal lexical projection as one that isn't dominated by *any* other lexical projections -- which is what is currently implemented. (@3ddiehead , right?)

Thanks, Nick.

**Comment by nvh4** [comment]
Yes - I completely agree, those are great examples to motivate revising the original definition.

**Comment by nkalivoda** [comment]
I also agree that a LexP dominated by any other LexP shouldn't be considered maximal. I just checked Ishihara (2014) and it doesn't seem like this redefinition conflicts with his analyses.

**Comment by 3ddiehead** [comment]
Yes, that is the implementation @jbellik 
I'm glad there is no conflict with Ishihara.
Here is the relevant tableau.  A second issue is whether after trimming [X.lex [Z.lex]] should incur a violation when compared with (X (Y (Z))). XP is the only phrase being counted for violations. It contains the leaves [X, Z] which is compared with the set of leaves for all the phi's of the pTree, [X, Y, Z], [Y, Z], and [Z]. Since the functional Y is trimmed out, there is no way for XP to match phonological trees made with X, Y, and Z as terminal nodes.

However, if the pTree being compared is (X(Z)) there is no violation.

I have two ideas:
1. There is no issue, this makes sense.
2. Stop trimming functional heads, leave dummy nodes.

**Comment by nkalivoda** [comment]
I don't understand. Gen doesn't allow deletion as in (1) in the tableau, so I don't think we need to worry about it.

**Comment by 3ddiehead** [comment]
@nkalivoda 
Right, okay, that makes sense. I didn't think so. But this means that if [X[Y.func[Z]]] goes through the MatchMaxLexical constraint it will basically always incur a violation. Check (3) in the second constraint column.

**Comment by nvh4** [comment]
If I understand correctly, I think the trimming needs to get rid of the YP layer while leaving in the head Y. The visibility settings make it such that particular XPs are(n't) visible to MatchXP, but should not affect the leaves. So it should look like the "alternative trimmed tree" in Jenny's earlier post: [.lex X Y.f [.lex Z]]. Then in the tableau, candidate 3 will satisfy MatchMaxLexical because the outermost lexical XP [X Y Z] is matched by (X Y Z).
