### ISSUE TITLE
extend build script

### ISSUE THREAD

**Issue by jbellik** [syntax-prosody-ot/main#455]
It would be helpful to have a build script that collects all the tree files that are relevant for the built-in analyses.

Probably we need to put these tree files in a subdirectory as well.

**Comment by jbellik** [comment]
- Look at the list of tree files that are getting loaded at the top of interface1.html and stick them in a subdirectory (of main/interface/, probably -- or of main/trees)
- Write a shell script to collect those into a built_in_trees.js file that interface1.html will load. This should sit in the build folder.
- jsbuild.sh should also call your tree building script

We'll need bat versions of the .sh scripts too!

**Comment by M130** [comment]
I built the shell and bat scripts but I am not sure if it is working correctly. I can't run the shell script I built because it kept stating permission denied when I tried to run it. However, I tried testing it from the jsbuild.sh and it seems to be running and the files are in the correct place but I am not sure how to test it from there. Branch name is tree-files-script
