### ISSUE TITLE
precisify StrongStartInit (strongStart_catInit)

### ISSUE THREAD

**Issue by jbellik** [syntax-prosody-ot/main#456]
- Ideally user should be able to specify parent and child categories -- one of them will need to be an option [?]
- category argument: Is it better for this to refer to the parent category (and penalize any initial child whose category is more than 1 step down -- i.e., provide i, penalize {w, ft, syll}), or refer to child category (and penalize parents that are 2+ steps up)
- what does the sister category have to be in relation to the initial child / parent categories? i.e., we know that {w phi} is a violation but do we want {ft w} to be a violation (I think yes), or [syll ft], or (syll Ft)?

[to be taken care of after AMP2020]

**Comment by jbellik** [comment]
Upon further communication with Nick K, this constraint is supposed to also penalize configurations like {w w (w)}, where the initial w isn't adjacent to a phi but does have a phi sister. That is, *any* higher category sister, not just the next sister, triggers a violation.

**Comment by nkalivoda** [comment]
That is correct, but it is my fault for not clarifying that earlier. It does not follow from the definition I provided, because I invented it for a system that didn't include {w w (w)} in Gen. However, it was most definitely the intention; if I had considered a system with a less restrictive Gen, I would have defined it in a more generalizable way.

I need to think about this some more, and consult with @jbellik, before we fix this, so please hold off for now.
